workos/workos-node

src/__snapshots__/workos.spec.ts.snap, src/common/exceptions/unprocessable-entity.exception.ts, src/workos.spec.ts
* fix tests to use snapshot
* add snapshot
=> fix: append unprocessable errors to exception message

src/sso/interfaces/promote-draft-connection-options.interface.ts, src/sso/sso.spec.ts, src/sso/sso.ts
This PR gives support for SSO promote draft connection.
https://app.asana.com/0/1160151042010922/1161174977831257
=> promote draft connection

src/sso/interfaces/promote-draft-connection-options.interface.ts, src/sso/sso.spec.ts, src/sso/sso.ts
=> rename id to token

.semaphore/npm.yml, .semaphore/semaphore.yml, README.md, package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts, yarn.lock
=> rename package to @workos-inc/node; remove version bump package

.semaphore/npm.yml, .semaphore/semaphore.yml, bin/restore-or-install
Run commands CI commands in parallel
=> refactor Semaphore

.semaphore/npm.yml
=> fix npm token

renovate.json
Set renovate to automerge updates for non-major versions.
=> automerge non-major updates

package.json, src/sso/__snapshots__/sso.spec.ts.snap
=> remove engines

src/common/exceptions/no-api-key-provided.exception.ts
This updates the error message to match the latest constructor function signature.
=> Update NoAPIKey exception message

package.json, src/audit-trail/audit-trail.spec.ts, src/audit-trail/audit-trail.ts, src/audit-trail/interfaces/event.interface.ts, src/audit-trail/interfaces/index.ts, src/directory-sync/directory-sync.spec.ts, src/directory-sync/directory-sync.ts, src/directory-sync/interfaces/index.ts, src/index.ts, src/sso/__snapshots__/sso.spec.ts.snap, src/sso/interfaces/index.ts, src/sso/sso.spec.ts, src/sso/sso.ts, src/workos.spec.ts, src/workos.ts
Also adding a barrel files for exports.
=> Change Audit Trail event type to string

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/sso/interfaces/profile.interface.ts, src/sso/sso.spec.ts
* On the API, we recently exposed raw_attributes, the original profile
response we receive from the IdP. This update passes this data through
the SDK.
* Updates the SDK to 0.5.0
=> Expose raw_attributes on Profile

package.json, src/portal/fixtures/list-organizations.json, src/portal/interfaces/list-organizations-options.interface.ts, src/portal/interfaces/organization-domain.interface.ts, src/portal/interfaces/organization.interface.ts, src/portal/portal.spec.ts, src/portal/portal.ts, src/workos.ts
* Returns a list of the organizations accessible to the provided
API key. Includes pagination functionality via the listMetadata
property.
=> Add Portal and expose listOrganizations()

src/index.ts, src/portal/fixtures/generate-link-invalid.json, src/portal/fixtures/generate-link.json, src/portal/interfaces/generate-portal-link-intent.interface.ts, src/portal/interfaces/index.ts, src/portal/portal.spec.ts, src/portal/portal.ts
* Adds an SDK method to generate an Admin Portal link.
=> Add generateLink to Portal

package.json, src/passwordless/interfaces/create-passwordless-session-options.interface.ts, src/passwordless/passwordless.spec.ts, src/sso/__snapshots__/sso.spec.ts.snap
This PR: 
- Removes inconsistent casing in the Passwordless Session options
- Bumps version to `0.8.2` for immediate release
=> Remove Inconsistent Casing

src/audit-trail/interfaces/event.interface.ts, src/directory-sync/interfaces/directory.interface.ts
Story details: https://app.clubhouse.io/workos/story/4513
=> Add `environment_id` to directory and event interfaces

package.json, src/sso/__snapshots__/sso.spec.ts.snap
Bumps version to 0.9.0 for release
=> Bump version from 0.8.4 to 0.9.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap
- Bumps package version to `0.9.2`
=> Bump Version

src/directory-sync/interfaces/user.interface.ts
Return a field which indicates if a User is active or suspended.
=> feat(api): Add state to Directory User

src/directory-sync/directory-sync.ts, src/directory-sync/interfaces/group.interface.ts, src/directory-sync/interfaces/user.interface.ts
This PR exposes the `groups` property when listing directory users.
=> Expose groups when listing directory users

src/directory-sync/directory-sync.ts
This PR exposes the groups property when retrieving a single directory user.
=> Expose groups when retrieving a single directory user

src/directory-sync/directory-sync.spec.ts, src/directory-sync/directory-sync.ts
This PR adds a `deleteDirectory` method for deleting directories.
=> Add `deleteDirectory` method

src/sso/interfaces/connection.interface.ts
https://linear.app/workos/issue/SDK-115/update-connection-status-to-connection-state-in-node-sdk
=> Update connection status to connection state

src/passwordless/interfaces/create-passwordless-session-options.interface.ts
https://linear.app/workos/issue/SDK-124/support-connection-param-for-create-passwordless-session-endpoint-in
=> Add connection param for Create Passwordless Session endpoint

src/audit-trail/__snapshots__/audit-trail.spec.ts.snap, src/common/exceptions/generic-server.exception.ts, src/common/exceptions/not-found.exception.ts, src/common/exceptions/unauthorized.exception.ts, src/common/exceptions/unprocessable-entity.exception.ts, src/common/interfaces/http-exception.interface.ts, src/common/interfaces/index.ts
https://github.com/workos-inc/workos-node/issues/380
=> fix(workos-node): Update exceptions to extend `Error`

src/organizations/organizations.spec.ts, src/organizations/organizations.ts
https://linear.app/workos/issue/SDK-197/add-deleteorganization-method-to-the-node-sdk
Adds a deleteOrganization method.
=> Add deleteOrganization method

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
The changes in #423 should be backwards compatible, but want to do a quick alpha release just to verify that everything is still correct.
=> v1.2.0-alpha

package-lock.json, src/webhooks/webhooks.spec.ts, src/webhooks/webhooks.ts
Add JSON.stringify to payload variable in computeSignature webhook method to resolve the 'Signature hash does not match the expected signature hash for payload' error
=> Stringify payload in webhooks validation to resolve error

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump patch version to release a fix in webhook validation.
=> Bump version to 2.1.1

src/organizations/organizations.spec.ts
=> Improve Organization unit tests

src/portal/portal.spec.ts
=> Improve Admin Portal unit tests

src/directory-sync/interfaces/user.interface.ts, src/webhooks/interfaces/index.ts, src/webhooks/interfaces/webhook-directory-group.interface.ts, src/webhooks/interfaces/webhook-directory-user.interface.ts, src/webhooks/interfaces/webhook-directory.interface.ts, src/webhooks/interfaces/webhook.interface.ts
=> Update Directory Sync Webhook Events types

src/audit-logs/audit-logs.spec.ts, src/audit-logs/audit-logs.ts, src/audit-logs/interfaces/audit-log-event-options.interface.ts, src/audit-logs/interfaces/create-audit-log-event-options.interface.ts, src/audit-logs/interfaces/index.ts, src/common/exceptions/bad-request.exception.ts, src/workos.ts
Adds `auditLogs` module with `createEvent` method for emitting audit log events.
=> Add `auditLogs` module

src/directory-sync/directory-sync.spec.ts, src/directory-sync/interfaces/group.interface.ts, src/directory-sync/interfaces/user.interface.ts, src/webhooks/interfaces/webhook-directory-group.interface.ts
* Expose the newly added field from the API on the SDK.
=> Add organization_id to Directory User and Directory Group

src/portal/interfaces/generate-portal-link-intent.interface.ts, src/portal/portal.spec.ts
Allows generating Admin Portal link for viewing an organizations Audit Log events
=> Add `audit_logs` Admin Portal intent

src/portal/interfaces/generate-portal-link-intent.interface.ts, src/portal/portal.spec.ts
=> Add `log_streams` Admin Portal intent

src/audit-logs/audit-logs.spec.ts, src/audit-logs/interfaces/audit-log-export-options.interface.ts
Changes from `v2.x` branch
- #729 
```
[ ] Yes
```
=> Merge v2.x branch

src/audit-trail/audit-trail.ts, src/audit-trail/interfaces/event.interface.ts, src/audit-trail/interfaces/index.ts, src/events/events.spec.ts, src/events/events.ts, src/events/interfaces/event.interface.ts, src/events/interfaces/get-events-options.interface.ts, src/events/interfaces/index.ts, src/events/interfaces/list-events-options.interface.ts, src/index.ts, src/workos.ts
Adding beta support for the Events API.
```
[ X ] Yes
```
=> Add Events API beta

src/audit-trail/audit-trail.ts, src/audit-trail/interfaces/event.interface.ts, src/audit-trail/interfaces/index.ts, src/events/events.spec.ts, src/events/events.ts, src/events/interfaces/event.interface.ts, src/events/interfaces/get-events-options.interface.ts, src/events/interfaces/index.ts, src/events/interfaces/list-events-options.interface.ts, src/index.ts, src/workos.ts
Adding `Events` API beta 
```
[ ] Yes
```
=> Add `Events` API  beta to v2.x

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
- `Events` API beta (#741)
```
[ ] Yes
```
=> Update to v2.19.0

src/users/interfaces/user.interface.ts
Should be `UnmanagedUser`.
```
[ ] Yes
```
=> Fix typo in `UnmanangedUser`

src/users/fixtures/list-users.json, src/users/fixtures/session.json, src/users/fixtures/user.json, src/users/interfaces/session.interface.ts, src/users/interfaces/user.interface.ts, src/users/serializers/session.serializer.ts, src/users/serializers/user.serializer.ts, src/users/users.spec.ts
workos/workos#22251 updated the shape of the session response. This updates the SDK to match it.
I'll update the docs as well to have the same shape as in this PR.
```
[x] Yes
```
=> Update Session interfaces to match API

src/users/interfaces/index.ts, src/users/interfaces/revoke-all-sessions-for-user-options.interface.ts, src/users/users.spec.ts, src/users/users.ts
Docs PR: https://github.com/workos/workos/pull/22357
```
[x ] Yes
```
=> Update revoke all sessions for user to use an interface

src/common/interfaces/index.ts, src/common/utils/fetch-and-deserialize.ts, src/common/utils/pagination.ts, src/directory-sync/directory-sync.spec.ts, src/directory-sync/directory-sync.ts, src/organizations/organizations.spec.ts, src/organizations/organizations.ts, src/sso/sso.ts, src/users/users.spec.ts, src/users/users.ts
=> Add auto-pagination

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to v3.0.0

src/common/exceptions/generic-server.exception.ts, src/workos.spec.ts, src/workos.ts
=> Surface rawData on GenericServerException

src/index.ts
* The class is useful to access externally when writing mocks that interface with our list endpoints.
```
[ ] Yes
```
=> Export AutoPaginatable

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to v3.1.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to v3.1.1

src/users/interfaces/enroll-user-in-mfa-factor.interface.ts, src/users/interfaces/index.ts, src/users/serializers/enroll-user-in-mfa-factor-options.serializer.ts, src/users/users.spec.ts, src/users/users.ts
=> Add `enrollUserInMfaFactor` method

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Update version for new release 3.2.1
```
[ ] Yes
```
=> Update version for new release 3.2.1

src/users/interfaces/update-user-options.interface.ts, src/users/serializers/update-user-options.serializer.ts, src/users/users.spec.ts
=> Add `emailVerifiedAt` to `updateUser`

src/users/interfaces/index.ts, src/users/interfaces/verify-email-code-options.interface.ts, src/users/interfaces/verify-email-options.interface.ts, src/users/users.spec.ts, src/users/users.ts
* Updating to latest changes in the API.
```
[ ] Yes
```
=> Migrate verifyEmail to verifyEmailCode

src/users/users.spec.ts, src/users/users.ts
=> Fix shape of `sendVerificationEmail`

src/users/users.spec.ts, src/users/users.ts
=> Update `verifyEmailCode` method to handle nested user object in return

src/users/interfaces/enroll-auth-factor.interface.ts, src/users/interfaces/index.ts, src/users/serializers/enroll-auth-factor-options.serializer.ts, src/users/serializers/index.ts, src/users/users.spec.ts, src/users/users.ts
=> Rename `enrollUserInMfaFactor` to `enrollAuthFactor`

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Changes on User Management Beta API:
- https://github.com/workos/workos-node/pull/861
- https://github.com/workos/workos-node/pull/860
- https://github.com/workos/workos-node/pull/858
- https://github.com/workos/workos-node/pull/857
- https://github.com/workos/workos-node/pull/856
- https://github.com/workos/workos-node/pull/855
- https://github.com/workos/workos-node/pull/854
- https://github.com/workos/workos-node/pull/853
- https://github.com/workos/workos-node/pull/851
- https://github.com/workos/workos-node/pull/850
```
[ ] Yes
```
=> Update to v3.7.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to v3.7.1

src/organization-domains/interfaces/organization-domain.interface.ts, src/organization-domains/serializers/organization-domain.serializer.ts
- Rename unverified organization domain state to LegacyVerified
- Add verification_strategy field
```
[ ] Yes
```
=> Adjust Organization Domain entity

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Updates SDK version to include new features: Serializer for Events and Domain Verification API 
```
[ ] Yes
```
=> Update version to 3.8.0

src/organization-domains/fixtures/get-organization-domain-pending.json, src/organization-domains/fixtures/get-organization-domain-verified.json, src/organization-domains/interfaces/organization-domain.interface.ts, src/organization-domains/organization-domains.spec.ts
=> Rename developer verification strategy to `manual`

src/user-management/interfaces/add-user-to-organization-options.interface.ts, src/user-management/interfaces/index.ts, src/user-management/interfaces/remove-user-from-organization-options.interface.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #884** 👈
=> Remove deprecated methods

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Updates `main` from the `3.x` branch, which we're using for minor/patch releases while we work on the next major release on `main`.
```
[ ] Yes
```
=> Update main from 3.x

src/user-management/fixtures/invitation.json, src/user-management/interfaces/invitation.interface.ts, src/user-management/serializers/invitation.serializer.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #892** 👈
* **PR #893**
* **PR #894**
* **PR #895**
* **PR #896**
=> Add `getInvitation` endpoint

src/user-management/fixtures/list-invitations.json, src/user-management/interfaces/list-invitations-options.interface.ts, src/user-management/serializers/list-invitations-options.serializer.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #893** 👈
* **PR #894**
* **PR #895**
* **PR #896**
=> Add `listInvitations` method

src/user-management/interfaces/send-invitation-options.interface.ts, src/user-management/serializers/send-invitation-options.serializer.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #894** 👈
* **PR #895**
* **PR #896**
=> Add `sendInvitation` method

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #895** 👈
* **PR #896**
=> Add `revokeInvitation` method

src/user-management/interfaces/list-users-options.interface.ts, src/user-management/serializers/list-users-options.serializer.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #898** 👈
=> Change `organization` to `organization_id` for `listUsers` method

src/sso/interfaces/authorization-url-options.interface.ts, src/sso/interfaces/get-profile-and-token-options.interface.ts, src/sso/sso.spec.ts, src/sso/sso.ts
```
[ ] Yes
```
* **PR #897** 👈
=> Standardize casing of Client ID to `clientId`

src/user-management/interfaces/delete-user-options.interface.ts, src/user-management/interfaces/index.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #899** 👈
=> Fix shape of parameters on `deleteUser` method

src/sso/__snapshots__/sso.spec.ts.snap, src/sso/sso.spec.ts, src/sso/sso.ts, src/user-management/__snapshots__/user-management.spec.ts.snap, src/user-management/interfaces/authorization-url-options.interface.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #901** 👈
* **PR #902**
=> Add `getAuthorizationURL` method to user management

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #904** 👈
=> Update url of `listAuthFactors` method

src/user-management/interfaces/enroll-auth-factor.interface.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #903** 👈
=> Update `enrollAuthFactor` method

src/user-management/interfaces/authenticate-with-email-verification-options.interface.ts, src/user-management/serializers/authenticate-with-email-verification.serializer.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #900** 👈
=> Add `authenticateWithEmailVerification` method

src/user-management/interfaces/index.ts, src/user-management/interfaces/verify-email-code-options.interface.ts, src/user-management/interfaces/verify-email-options.interface.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #906** 👈
=> Change `verifyEmailCode` to `verifyEmail`

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #905** 👈
=> Update endpoint on `sendVerificationEmail`

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #907** 👈
=> Update `sendPasswordResetEmail` URL

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #908** 👈
=> Update url for `resetPassword` method

src/user-management/interfaces/authenticate-with-organization-selection.interface.ts, src/user-management/serializers/authenticate-with-organization-selection-options.serializer.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #909** 👈
=> Add `authenticateWithOrganizationSelection` method

src/user-management/interfaces/authentication-response.interface.ts, src/user-management/serializers/authentication-response.serializer.ts
```
[ ] Yes
```
* **PR #912** 👈
=> Add `organizationId` to `AuthenticationResponse`

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #914** 👈
=> Modify `sendMagicAuthCode` to return void

src/mfa/interfaces/factor.interface.ts, src/mfa/interfaces/totp.interface.ts, src/mfa/serializers/factor.serializer.ts, src/mfa/serializers/totp.serializer.ts
```
[ ] Yes
```
* **PR #917** 👈
=> Update shape of `Factor`

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
Update delete user path
```
[ ] Yes
```
=> User Management - Update delete user path

src/common/interfaces/event.interface.ts, src/common/serializers/event.serializer.ts
```
[ ] Yes
```
* **PR #919** 👈
=> Add user event types

src/user-management/interfaces/authenticate-with-code-options.interface.ts, src/user-management/interfaces/authenticate-with-email-verification-options.interface.ts, src/user-management/interfaces/authenticate-with-magic-auth-options.interface.ts, src/user-management/interfaces/authenticate-with-options-base.interface.ts, src/user-management/interfaces/authenticate-with-organization-selection.interface.ts, src/user-management/interfaces/authenticate-with-password-options.interface.ts, src/user-management/interfaces/authenticate-with-totp-options.interface.ts, src/user-management/user-management.spec.ts
```
[ ] Yes
```
* **PR #921** 👈
=> Audit `authenticateWith*` methods and extract out a base type

src/user-management/interfaces/update-user-options.interface.ts, src/user-management/serializers/update-user-options.serializer.ts
```
[ ] Yes
```
* **PR #923** 👈
=> Update `updateUser` options

src/common/interfaces/event.interface.ts, src/common/serializers/event.serializer.ts
```
[ ] Yes
```
* **PR #922** 👈
=> Add `OrganizationMembership` event types

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
```
[ ] Yes
```
* **PR #924** 👈
=> Return an `Invitation` from `revokeInvitation`

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Update axios and bump sdk version
```
[ ] Yes
```
=> Update axios and change dependency constraint and bump to v.3.9.2

src/sso/sso.ts
=> Serialize list /connections params

src/user-management/fixtures/user.json, src/user-management/interfaces/user.interface.ts, src/user-management/serializers/user.serializer.ts, src/user-management/user-management.spec.ts
=> Add profile_picture_url attribute to the user object

src/common/utils/fetch-client.ts, src/common/utils/test-utils.ts
Fixes #968
This PR fixes cases where our APIs do not return a response.
```
[ ] Yes
```
=> Fix no response API calls

src/events/events.spec.ts, src/sso/sso.spec.ts
While we check list parameters for being correctly serialized in user management and directory sync, we were missing some checks in the SSO and Events 
```
[ ] Yes
```
=> Update tests to check for search params

src/user-management/interfaces/authenticate-with-refresh-token-options.interface.ts, src/user-management/interfaces/authentication-response.interface.ts, src/user-management/interfaces/index.ts, src/user-management/interfaces/revoke-session-options.interface.ts, src/user-management/serializers/authenticate-with-refresh-token.options.serializer.ts, src/user-management/serializers/authentication-response.serializer.ts, src/user-management/serializers/index.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
Adds types/endpoints for session management.
```
[X] Yes
```
=> Add session-management endpoints

src/user-management/fixtures/organization-membership.json, src/user-management/interfaces/create-organization-membership-options.interface.ts, src/user-management/interfaces/organization-membership.interface.ts, src/user-management/interfaces/role.interface.ts, src/user-management/interfaces/update-organization-membership-options.interface.ts, src/user-management/serializers/create-organization-membership-options.serializer.ts, src/user-management/serializers/organization-membership.serializer.ts, src/user-management/serializers/update-organization-membership-options.serializer.ts, src/user-management/user-management.spec.ts, src/user-management/user-management.ts
New "role" parameter which is used in the User Management OrganizationMemberships API
```
[ ] Yes
```
=> Add role parameter to User Management OrganizationMemberships API

src/user-management/interfaces/authentication-response.interface.ts
This was necessary during pre-release, but no longer.
```
[ ] Yes
```
=> Make auth tokens non-optional

src/common/interfaces/event.interface.ts, src/common/serializers/event.serializer.ts
Fixes https://linear.app/workos/issue/AUTH-2932/remove-userimpersonated-in-node-sdk
```
[ ] Yes
```
=> Remove separate user.impersonated event

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Update to v7.0.0

.github/workflows/release.yml
=> Remove dry run flag from release

src/common/interfaces/event.interface.ts, src/common/serializers/event.serializer.ts, src/organizations/interfaces/organization-domain.interface.ts
Introduces support for [organization events](https://workos.com/docs/events/user-management/organization)
```
[x] Yes
```
=> feat: Organization events

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Update to v7.1.0

src/user-management/interfaces/authentication-response.interface.ts, src/user-management/serializers/authentication-response.serializer.ts, src/user-management/user-management.spec.ts
=> Add authenticationMethod to the authentication response serializer

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
Exposes method to find an invitation by token.
```
[x] Yes
```
https://github.com/workos/workos/pull/27785
=> Add find invitation by token method

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Update version to 7.9.0 - includes adding PKCE params to UM authentication methods 
```
[ ] Yes
```
=> Update version to 7.9.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bumps to v7.10.0
```
[ ] Yes
```
=> Bump to v7.10.0

package.json
Fix path to types.
```
[ ] Yes
```
=> Fix typings path

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Fix typings and release

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bumps to v7.13.0.
```
[ ] Yes
```
=> Bump to v7.13.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
This version includes:
- https://github.com/workos/workos-node/pull/1059
```
[ ] Yes
```
=> Bump version to 7.14.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump to v7.15.0.
```
[ ] Yes
```
=> Bump to v7.15.0

src/user-management/interfaces/refresh-and-seal-session-data.interface.ts, src/user-management/user-management.ts
Fix invalid session cookie enum name.
```
[ ] Yes
```
=> Fix invalid session cookie enum name

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump to version 7.17.1.
```
[ ] Yes
```
=> Bump to version 7.17.1

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump version to 7.19.0 to release Cloudflare worker fix.
```
[ ] Yes
```
=> Bump version to 7.19.0

package.json, src/organizations/interfaces/update-organization-options.interface.ts, src/organizations/organizations.spec.ts, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
- Make name optional when updating an Organization
```
[ ] Yes
```
=> Make name optional when updating an Organization

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump version to 7.22.0

src/index.ts
- Exports types related to FGA module
```
[ ] Yes
```
=> Export FGA types

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Releases a new version `v7.22.1` which includes:
- #1106 
```
[ ] Yes
```
=> Bump version to v7.22.1

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump version to 7.25.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump version to 7.25.1

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to 7.27.1

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Releases a new version `v7.27.2` which includes
- #1124 
- #1125 
```
[ ] Yes
```
=> Bump version to v7.27.2

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to 7.27.3

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to 7.27.4

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to 7.27.5

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Minor version bump to release #1137 
```
[ ] Yes
```
=> Bump minor version 7.28.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Adding `auditLogs.createSchema`, so need a new minor version.
```
[ ] Yes
```
=> Bump to 7.29.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump version to v7.30.0

src/widgets/fixtures/get-token-error.json, src/widgets/fixtures/token.json, src/widgets/interfaces/get-token.ts, src/widgets/widgets.spec.ts, src/widgets/widgets.ts, src/workos.ts, tslint.json
=> Add `widgets`

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump version to v7.30.1

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Includes #1164 
```
[ ] Yes
```
=> Bump version to v7.31.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump to version 7.32.0.
```
[ ] Yes
```
=> Bump to version 7.32.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump to version 7.33.1 to fix audit log schema creation bug.
```
[ ] Yes
```
=> Bump to version 7.33.1

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to v7.34.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Hotfix for iron-session default ttl.
```
[ ] Yes
```
=> Bump to v7.35.1

src/actions/actions.ts
User reported bug.
```
[ ] Yes
```
=> Tolerance is in ms, 300 is too low a default

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump to version 7.36.0.
```
[ ] Yes
```
=> Bump to version 7.36.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Updates version tags in code
```
[ ] Yes
```
=> version bump to 7.36.3

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump version number (patch) to account for change in #1210.
```
[ ] Yes
```
=> Bump to v7.37.1

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump to:
* [Add permissions to roles events and API](https://github.com/workos/workos-node/pull/1216)
* [Update Session#refresh() to return all JWT claims (permissions, role, entitlements, etc.)](https://github.com/workos/workos-node/pull/1218)
```
[ ] Yes
```
=> Bump to version 7.38.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Version bump that includes:
- [add lastSignInAt to user](https://github.com/workos/workos-node/pull/1220)
```
[ ] Yes
```
=> bump version to 7.39.0

src/user-management/user-management.spec.ts, src/user-management/user-management.ts
Convenience method for accessing the associated api endpoint
```
[x] Yes
```
^ docs are coming but looking to get this out in a preview release ahead of time.
=> Add getUserByExternalId

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to v.7.42.0

src/widgets/interfaces/get-token.ts
=> Make the scopes field optional

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump to v7.44.0.
```
[ ] Yes
```
=> Bump to v7.44.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to v7.45.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Version bump that includes:
- https://github.com/workos/workos-node/pull/1255
- https://github.com/workos/workos-node/pull/1256
```
[ ] Yes
```
=> bump version to 7.46.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Bump to v7.48.0.
```
[ ] Yes
```
=> Bump to v7.48.0

src/common/interfaces/event.interface.ts, src/common/serializers/event.serializer.ts, src/user-management/interfaces/authentication-radar-risk-detected-event.interface.ts, src/user-management/interfaces/index.ts, src/user-management/serializers/authentication-radar-risk-event-serializer.ts
=> feat: add authentication.radar_risk_detected event

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
=> Bump to v7.50.0

src/user-management/fixtures/list-organization-memberships.json, src/user-management/interfaces/organization-membership.interface.ts, src/user-management/serializers/organization-membership.serializer.ts, src/user-management/user-management.spec.ts
Serialize and surface the organization name in the list organization membership call. Addressing https://github.com/workos/workos-node/issues/1284
```
[X] No
```
=> Add organization name to list organization memberships

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
version bump that includes:
- https://github.com/workos/workos-node/pull/1282
- https://github.com/workos/workos-node/pull/1288
```
[ ] Yes
```
=> bump version to v7.53.0

package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Update version to 7.59.0 to include prompt parameter in getAuthorizationUrl method
https://github.com/workos/workos-node/pull/1304 
```
[ ] Yes
```
=> Update version to 7.59.0

src/organizations/interfaces/list-organization-feature-flags-options.interface.ts, src/organizations/organizations.spec.ts, src/organizations/organizations.ts
- Add pagination support to `listOrganizationFeatureFlags`
```
[ ] Yes
```
=> Add pagination support to listOrganizationFeatureFlags

package-lock.json, package.json, src/sso/__snapshots__/sso.spec.ts.snap, src/workos.ts
Version bump to 7.70.0
- Bump version to 7.70.0 in package.json, package-lock.json, and src/workos.ts
- Update snapshot tests with new version
- https://github.com/workos/workos-node/pull/1358
=> Bump version to 7.70.0
