package.json
src/sso/__snapshots__/sso.spec.ts.snap

Our latest published version is actually 0.0.22 but package.json had 0.0.3...
https://www.npmjs.com/package/@workos-inc/js?activeTab=versions

fix version

---

src/directory-sync/directory-sync.spec.ts
src/directory-sync/directory-sync.ts
src/directory-sync/interfaces/list-groups-options.interface.ts
src/directory-sync/interfaces/list-users-options.interface.ts

* Uses `/directory_users` instead of `/directories/:id/users`
* Uses `/directory_groups` instead of `/directories/:id/groups`

Rename endpoints to fetch Directory Groups and Users

---

jest.config.js
package.json
src/audit-trail/audit-trail.spec.ts
src/audit-trail/audit-trail.ts
src/audit-trail/interfaces/event-options.interface.ts
src/audit-trail/interfaces/event.interface.ts
src/audit-trail/interfaces/list-events-options.interface.ts
src/common/interfaces/index.ts
src/directory-sync/interfaces/directory.interface.ts
src/sso/__snapshots__/sso.spec.ts.snap

* Removing `Event` from common types
* Re-factoring current `Event` to `EventOptions` when creating events
* Creating `Event` for returned Audit Trail events
* Bump version to 0.4.0
* Update old snapshots

Add method to fetch Audit Trail events

---

src/portal/fixtures/create-organization-invalid.json
src/portal/fixtures/create-organization.json
src/portal/portal.spec.ts
src/portal/portal.ts

* Adds the ability to create an organization via the SDK for use
with the Admin Portal.

Add createOrganization to Portal

---

src/portal/interfaces/list-organizations-options.interface.ts
src/portal/portal.spec.ts

* Modifies the arg to accept an array of strings, instead of a
string.

Rename listOrganizations arg "domain" to "domains"

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap

* Had an error with the release of 0.6.0 and the `package.json` did not properly update. Bumping us to 0.6.1 to get us back into a proper state.

@willmanduffy Bump @workos-inc/node to 0.6.1

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/sso/interfaces/profile.interface.ts
src/sso/sso.spec.ts

* Passes the `connection_id` Profile object attribute through to the SDK. We currently expose `connection_id` via the `/sso/token` API endpoint.
* Updates the SDK version to `0.8.0`.

Expose `connection_id` on Profile Objects

---

src/passwordless/interfaces/create-passwordless-session-options.interface.ts
src/passwordless/passwordless.spec.ts

This PR adds the capability to pass a `redirect_uri` option when creating a passwordless session. This allows the user to choose their desired callback from the Redirect URIs they've configured in the WorkOS Dashboard.
Currently, the callback falls back to the designated default Redirect URI.

Support `redirect_uri` Option for Creating Passwordless Sessions

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap

Bump SDK version fo `0.8.1`, including:
- Support for a `redirect_uri` option when creating Passwordless Sessions

Bump Version

---

package.json
src/passwordless/passwordless.spec.ts
src/passwordless/passwordless.ts
src/sso/__snapshots__/sso.spec.ts.snap

This PR fixes an issue with creating a passwordless session where we were using the wrong name when passing the `redirect_uri` up to the API.

Use the correct parameter name for `redirect_uri`

---

src/audit-trail/interfaces/event.interface.ts
src/directory-sync/interfaces/directory.interface.ts

https://app.clubhouse.io/workos/story/4514/node-remove-project-id-from-directory-and-event-interfaces
Removes `project_id` from the directory and event interfaces

Removing project_id from directory and event interfaces

---

package.json
src/portal/portal.spec.ts
src/portal/portal.ts
src/sso/__snapshots__/sso.spec.ts.snap

* We need to translate `returnUrl` (the natural casing in our Node SDK) to
`return_url` which our API will accept.

Resolve an issue where we were not properly sending `returnUrl` to the API

---

src/sso/interfaces/list-connections-options.interface.ts
src/sso/sso.spec.ts
src/sso/sso.ts

https://linear.app/workos/issue/SDK-25/add-get-connections-for-node-sdk
Adds a `getConnection` method wrapping the `/connections/:id` endpoint and a `listConnections` method wrapping the `/connections` endpoint

Add getConnection and listConnections methods

---

src/directory-sync/interfaces/directory.interface.ts

- Removes `bearer_token` attribute from `Directory` interface

Remove Unneeded Attribute from `Directory` Interface

---

src/sso/interfaces/connection-type.enum.ts

- Updates available properties of the `ConnectionTypes` interface to support [those offered by the WorkOS API](https://workos.com/docs/reference#profile-connection_type).

Update `ConnectionTypes` Interface

---

src/sso/interfaces/list-connections-options.interface.ts

- Adds support for an `organization_id` option to the `listConnections` method. Allows for retrieving a list of all Connections associated with the given `organization_id`.

Add `organization_id` Option to `listConnections`

---

src/directory-sync/interfaces/directory.interface.ts

- Adds `invalid_credentials` as a possible value for the Directory interface `state` attribute. This reflects the most up-to-date, available values for the Directory state enum provided by the WorkOS API.

Add `invalid_credentials` to Directory Interface `state`

---

src/portal/portal.ts

Domains aren't required in the API when creating Organizations. This PR makes the argument optional.

feat(workos-node): Make `domains` optional when creating Organizations

---

src/directory-sync/interfaces/index.ts

So that `import { UserWithGroups } from '@workos-inc/node'` works as expected.

Export `UserWithGroups` at the top-level

---

src/portal/portal.spec.ts
src/portal/portal.ts

The data returned from the `portal/generate_link` endpoint is in the form `{ "link": "<LINK>" }`, but the return type of `generateLink` in the SDK is a `string`.
This PR extracts the `link` property from the API response and returns it so that the runtime type matches the static type.

Fix data returned from `generateLink`

---

src/portal/portal.spec.ts
src/portal/portal.ts

Rather than the approach taken in #363, this PR changes the return type of `generateLink` to match the data being returned.
This is consistent with the usage we show in the docs.

Change generate link return type

---

src/directory-sync/interfaces/user.interface.ts

This PR exposes the `idp_id` field for directory users.
Resolves SDK-99.

Expose `idp_id` for directory users

---

src/sso/interfaces/connection.interface.ts

This PR removes the following deprecated fields from `Connection`s:
- `oauth_uid`
- `oauth_secret`
- `oauth_redirect_uri`
- `saml_entity_id`
- `saml_idp_url`
- `saml_relying_party_trust_cert`
- `saml_x509_certs`
We also expose the following new field: `organization_id`.
This is a breaking change.
Resolves SDK-139.

Remove deprecated Connection fields

---

src/sso/__snapshots__/sso.spec.ts.snap
src/sso/interfaces/authorization-url-options.interface.ts
src/sso/interfaces/get-profile-and-token-options.interface.ts
src/sso/sso.spec.ts
src/sso/sso.ts

This PR removes support for the deprecated `projectID` parameter.
This is a breaking change that will be part of `v1.0.0`.
Resolves SDK-161.

Remove support for deprecated `projectID` parameter

---

src/audit-trail/audit-trail.ts
src/common/interfaces/get-options.interface.ts
src/common/interfaces/index.ts
src/directory-sync/directory-sync.ts
src/organizations/organizations.ts
src/sso/interfaces/get-profile-options.interface.ts
src/sso/sso.spec.ts
src/sso/sso.ts
src/workos.ts

This PR adds a `getProfile` (no, not that one) method for calling the `/sso/profile` endpoint.
Resolves SDK-189.

Add `getProfile` method

---

src/passwordless/interfaces/create-passwordless-session-options.interface.ts
src/passwordless/passwordless.ts

This PR adds an optional `expiresIn` property to the `CreatePasswordlessSessionOptions`.
This property can be used to provide the time until the session expires (in seconds).

Add `expiresIn` to `CreatePasswordlessSessionOptions`

---

.gitignore
.npmignore
package.json
src/index.ts
src/workos.ts
tsconfig.json
tslint.json

This PR adds a named `WorkOS` export for the SDK to facilitate more ergonomic usage by CommonJS users.
```js
const { WorkOS } = require('@workos-inc/node');
const workos = new WorkOS('sk_example_123456789');
```
```ts
import WorkOS from '@workos-inc/node';
const workos = new WorkOS('sk_example_123456789');
```
or
```ts
import { WorkOS } from '@workos-inc/node';
const workos = new WorkOS('sk_example_123456789');
```
Resolves SDK-76.

Add named export for CommonJS consumers

---

src/directory-sync/directory-sync.spec.ts
src/directory-sync/directory-sync.ts
src/directory-sync/interfaces/user.interface.ts

This PR exposes the `custom_attributes` field for directory users.
We provide a `TCustomAttributes` type parameter that allows for the type of `custom_attributes` to be customized based on which custom attributes are defined. By default we treat this as a `Record<string, unknown>`.
Resolves SDK-245.

Expose `custom_attributes` for directory users

---

src/directory-sync/interfaces/directory.interface.ts
src/organizations/interfaces/organization.interface.ts
src/sso/interfaces/connection.interface.ts

https://linear.app/workos/issue/SDK-250/add-created-at-and-updated-at-fields-to-node-sdk
Adds `created_at` and `updated_at` fields to Connections, Directories, and Organizations.

Add created_at and updated_at fields

---

src/organizations/fixtures/create-organization.json
src/organizations/fixtures/get-organization.json
src/organizations/fixtures/list-organizations.json
src/organizations/fixtures/update-organization.json
src/organizations/interfaces/create-organization-options.interface.ts
src/organizations/interfaces/index.ts
src/organizations/interfaces/organization.interface.ts
src/organizations/organizations.spec.ts
src/organizations/organizations.ts

This PR adds support for the `allow_profiles_outside_organization` field for organization objects and operations.
Resolves SDK-256.

Add support for `allow_profiles_outside_organization` for organizations

---

src/sso/__snapshots__/sso.spec.ts.snap
src/sso/interfaces/profile.interface.ts
src/sso/sso.spec.ts

This PR exposes the `organization_id` field on profiles.
Resolves SDK-262.

Expose `organization_id` on profiles

---

src/webhooks/interfaces/index.ts
src/webhooks/interfaces/webhook-directory.interface.ts
src/webhooks/interfaces/webhook.interface.ts

This PR makes some adjustments to the webhook types:
- Account for the difference `state` values returned for directories in webhook payloads 
- Export the individual webhook types

Adjust webhook types

---

src/audit-trail/audit-trail.spec.ts
src/common/interfaces/list.interface.ts
src/organizations/fixtures/list-organizations.json
src/organizations/organizations.spec.ts

This PR updates the `List` type to use `list_metadata` instead of `listMetadata`.
This is a breaking change.
Resolves SDK-313.

Use non-deprecated form of `list_metadata`

---

src/directory-sync/directory-sync.spec.ts
src/directory-sync/directory-sync.ts

https://linear.app/workos/issue/SDK-327/get-a-directory-endpoint-for-node-sdk
Adds a Get a Directory endpoint for Directory Sync.

Add Get a Directory endpoint

---

src/directory-sync/interfaces/group.interface.ts
src/directory-sync/interfaces/user.interface.ts
src/webhooks/interfaces/webhook.interface.ts

Fix missing attribute on user webhook events
> Note: I haven't looked into whether `directory_id` should be present on all uses of the `User` interface (or if this "merged" type is only used in webhooks

Fix missing directory_id on user webhook event

---

src/webhooks/webhooks.ts

According to the documentation, tolerances are between '3-5 minutes'. This library is instead validating against 180 milliseconds
This PR updates the default values to 3 minutes

Update default tolerance to 3 minutes

---

src/sso/__snapshots__/sso.spec.ts.snap
src/sso/interfaces/authorization-url-options.interface.ts
src/sso/sso.spec.ts
src/sso/sso.ts

This PR adds support for the `organization` parameter to initiate SSO.
As part of this, the `domain` parameter has also been deprecated in favor of `organization`.
Resolves SDK-353.

Add support for `organization` parameter

---

src/index.ts

I'm building a wrapper around the WorkOS client in TypeScript and noticed that types such as `Organization` and `CreateOrganizationOptions` are not exported by `@workos-inc/node`. Instead I had to import them from `@workos-inc/node/lib/organizations/interfaces`.

Export organization type definitions at top level

---

src/directory-sync/interfaces/list-directories-options.interface.ts

resolves SUP-267 https://linear.app/workos/issue/SUP-267/node-sdk-add-organization-id-filter-to-list-directories-method

Add organization_id parameter to listDirectories method

---

src/mfa/interfaces/challenge-factor-options.ts
src/mfa/interfaces/verify-factor-options.ts
src/mfa/mfa.spec.ts
src/mfa/mfa.ts

Currently the enrollment method won't work as its passing camel cased arguments directly to the HTTP request.
- Fixes `enrollFactor` method
- Updates `challengeFactor` and `verifyFactor` method to consume camel cased arguments for consistency
- Updates unit tests to match the request body for mocks so that this logic is covered going forward
Note: I've tested against the API

Fix casing of MFA API arguments

---

src/sso/sso.spec.ts

Many of the unit tests are mock HTTP requests without doing any matching on the path or request body. By explicating matching those properties we can help ensure that our API requests are formatted properly.
I will be splitting up the improvements into separate PRs. See sub-issues of https://linear.app/workos/issue/SDK-407/improve-testing-strategy-in-node-sdk

Improve SSO unit tests

---

src/directory-sync/directory-sync.spec.ts

Resolves SDK-410.
- Adds both pathname and request body matching for all Axios mocks
- Adds actual typed responses to all mock API calls and asserts results (many methods didn't have assertions on the response)

Improve Directory Sync unit tests

---

src/audit-trail/interfaces/event.interface.ts
src/directory-sync/directory-sync.spec.ts
src/directory-sync/interfaces/directory.interface.ts
src/mfa/interfaces/factor.interface.ts
src/mfa/mfa.spec.ts

This PR removes the `environment_id` fields from various objects, as these fields are not returned by the API.

Remove `environment_id` fields

---

src/common/exceptions/unprocessable-entity.exception.ts
src/mfa/interfaces/verify-factor-response.ts
src/mfa/mfa.spec.ts
src/workos.ts

API currently can return `UnprocessableEntityException` with `code` and `message` properties. The Node SDK currently does not work with such responses, rather it always expects an `errors` property that it maps to generate a unique message.
This expands the `UnprocessableEntityException` error in the SDK to handle both cases.
I'm also removing a response type in the MFA API that can never be returned due to how the HTTP client handles non 200 status codes.
Should also be mentioned that this will also fix other exceptions outside of the MFA API as well.

Fix handling of `UnprocessableEntityException` responses

---

src/directory-sync/directory-sync.spec.ts
src/directory-sync/interfaces/group.interface.ts

Update the Directory Group interface to add currently missing fields being returned by the API. Specifically `idp_id`, `created_at` and `updated_at`.

Add idp_id, created_at and updated_at fields to Directory Group interface

---

src/mfa/interfaces/challenge.interface.ts

Updates the `expires_at` field to be nullable in the MFA Challenge interface.

Make expires_at nullable in MFA challenge interface

---

src/common/exceptions/not-found.exception.ts
src/workos.spec.ts
src/workos.ts

Fixes misleading 404 messages returned from the API and refactors error mapping.
Before:
```
The requested path '/audit_logs/events' could not be found.
err: {
"type": "NotFoundException",
"message": "The requested path '/audit_logs/events' could not be found.",
"stack":
NotFoundException: The requested path '/audit_logs/events' could not be found.
at WorkOS.<anonymous> (....)
"status": 404,
"name": "NotFoundException"
}
```
After:
```
Audit Log Validator not found: 'user.login_succeeded.1'.
err: {
"type": "NotFoundException",
"message": "Audit Log Validator not found: 'user.login_succeeded.1'.",
"stack":
NotFoundException: Audit Log Validator not found: 'user.login_succeeded.1'.
at WorkOS.handleAxiosError (...)
"status": 404,
"name": "NotFoundException",
"code": "entity_not_found"
}
```

Fix misleading 404 messages

---

src/common/interfaces/workos-options.interface.ts
src/workos.spec.ts
src/workos.ts

This PR adds support for customizing the underlying Axios client.
Resolves SDK-577.

Allow customizing Axios client

---

.semaphore/semaphore.yml
src/sso/__snapshots__/sso.spec.ts.snap
src/sso/interfaces/profile.interface.ts
src/sso/sso.spec.ts

Adds groups attribute to user profile. Available behind a feature flag.
```
[ ] Yes
```

Add groups attribute to user profile

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/sso/sso.spec.ts
src/sso/sso.ts
yarn.lock

Removes the dependency on `query-string` and replaces it with built-in Node API's.
[We've received automated version bumps for `query-string`](https://github.com/workos/workos-node/pull/696), but given the new version requires ESM (which we don't currently use), and how small our usage of `query-string` is, it seems easier to remove it.
```
[ ] Yes
```

Remove `query-string` dependency

---

src/audit-logs/audit-logs.spec.ts
src/audit-logs/interfaces/audit-log-export-options.interface.ts

Adds `actor_ids` and deprecates `actors` in favor of `actor_names`.
```
[x] Yes
```

Add `actor_ids` parameter to `createExport`

---

.semaphore/npm.yml

Looks like this was merged _after_ the previous `v2.17.0` tag which is why it wasn't in the `v2.x` branch.
```
[ ] Yes
```

Fix CI (#707)

---

src/sso/interfaces/connection.interface.ts

Add validating state to ConnectionDomain interface
```
[x] Yes
```

Add validating state to ConnectionDomain interface

---

src/events/interfaces/list-events-options.interface.ts

Use snake case for range params in the Events API. This makes Events consistent with the rest of our API.
```
[ ] Yes
```

Use snake case for Events range params (v2.x)

---

src/audit-logs/audit-logs.spec.ts
src/audit-trail/audit-trail.spec.ts
src/directory-sync/directory-sync.spec.ts
src/events/events.spec.ts
src/portal/portal.spec.ts
src/workos.spec.ts

This PR fixes a typo in the imported `MockAdapter` from `axios-mock-adapter`.
Same as #765, but for the `v2.x` branch.
```
[ ] Yes
```

Fix typo in `MockAdapter` (v2.x)

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/workos.ts

Bumping the API version now to clarify that:
* `main` is the v3 development branch
* `v2.x` should be used for current API releases
```
[ ] Yes
```

Bump major version to v3.0.0

---

src/audit-logs/audit-logs.spec.ts
src/audit-trail/audit-trail.spec.ts
src/directory-sync/directory-sync.spec.ts
src/events/events.spec.ts
src/portal/portal.spec.ts
src/workos.spec.ts

This PR fixes a typo in the imported `MockAdapter` from `axios-mock-adapter`.
```
[ ] Yes
```

Fix typo in `MockAdapter`

---

src/users/interfaces/user.interface.ts

These fields will always be present, but potentially `null`, rather than optionally present on the object.
```
[ ] Yes
```

Update optional fields on `User` to be nullable

---

src/directory-sync/directory-sync.spec.ts
src/directory-sync/directory-sync.ts
src/directory-sync/interfaces/directory-user.interface.ts
src/directory-sync/interfaces/index.ts
src/directory-sync/utils/get-primary-email.spec.ts
src/directory-sync/utils/get-primary-email.ts
src/webhooks/interfaces/webhook-directory-user.interface.ts

* This is a breaking change to rename the User interface, which is taking up a namespace that we would otherwise like to use, to DirectoryUser. This aligns the interface with the naming used elsewhere across the WorkOS platform.
```
[x] Yes
```

Rename User interface to DirectoryUser

---

src/directory-sync/directory-sync.spec.ts
src/directory-sync/directory-sync.ts
src/directory-sync/interfaces/directory-group.interface.ts
src/directory-sync/interfaces/directory-user.interface.ts
src/directory-sync/interfaces/index.ts

* This is a breaking change to rename the Group interface. While not strictly necessary as the User -> DirectoryUser rename was, this is done to keep consistency across the SDK and to closer align the Node SDK interfaces with other SDKs and with the rest of our platform.
```
[x] Yes
```

Rename Group interface to DirectoryGroup

---

src/directory-sync/directory-sync.ts
src/directory-sync/interfaces/index.ts
src/directory-sync/interfaces/list-directory-users-options.interface.ts

This frees up the `ListUserOptions` name for user management.
```
[ ] Yes
```

Rename ListUsersOptions to ListDirectoryUserOptions

---

src/audit-logs/audit-logs.spec.ts
src/audit-logs/audit-logs.ts
src/audit-logs/interfaces/audit-log-export-options.interface.ts
src/audit-logs/interfaces/audit-log-export.interface.ts
src/audit-logs/interfaces/create-audit-log-event-options.interface.ts
src/audit-logs/serializers/audit-log-export-options.serializer.ts
src/audit-logs/serializers/audit-log-export.serializer.ts
src/audit-logs/serializers/create-audit-log-event-options.serializer.ts
src/audit-logs/serializers/index.ts
src/common/utils/workos-mock-response.ts
src/workos.ts

* Part of a wider initiative to migrate our Node SDK to camel case for the 3.0.0 release.
* Migrates the Audit Log module to camel case.
```
[x] Yes
```

Migrate Audit Logs to camelCased

---

src/events/events.spec.ts
src/events/events.ts
src/events/interfaces/event.interface.ts
src/events/interfaces/list-events-options.interface.ts
src/events/serializers/event.serializer.ts

* Part of a wider initiative to migrate our Node SDK to camel case for the 3.0.0 release.
* Migrates the Events module to camel case.
```
[x] Yes
```

Migrate Events to camelCased

---

src/users/interfaces/user.interface.ts

Similar to the existing `google_oauth_profile_id`, this also adds `microsoft_oauth_profile_id` which we support.
```
[ ] Yes
```

Add `microsoft_oauth_profile_id` to `UnmanagedUser`

---

src/passwordless/interfaces/create-passwordless-session-options.interface.ts
src/passwordless/interfaces/index.ts
src/passwordless/interfaces/passwordless-session.interface.ts
src/passwordless/passwordless.ts
src/passwordless/serializers/passwordless-session.serializer.ts

* Part of a wider initiative to migrate our Node SDK to camel case for the 3.0.0 release.
* Migrates the Passwordless module to camel case.
```
[x] Yes
```

Migrate Passwordless to camelCased

---

src/users/interfaces/index.ts
src/users/interfaces/update-user-password-options.interface.ts
src/users/serializers/index.ts
src/users/serializers/update-user-password-options.serializer.ts
src/users/serializers/update-user-password.serializer.ts
src/users/users.spec.ts
src/users/users.ts

Adds the update user password method for the user management API
```
[ ] Yes
```

Add update user password method

---

src/users/interfaces/index.ts
src/users/interfaces/update-user-options.interface.ts
src/users/serializers/index.ts
src/users/serializers/update-user-options.serializer.ts
src/users/users.spec.ts
src/users/users.ts

Adds an `updateUser` method for user management
```
[ ] Yes
```

Add update user method

---

src/audit-trail/audit-trail.ts
src/common/interfaces/list.interface.ts
src/common/serializers/list.serializer.ts
src/directory-sync/directory-sync.spec.ts
src/directory-sync/directory-sync.ts
src/events/events.spec.ts
src/events/events.ts
src/organizations/organizations.ts
src/sso/sso.ts
src/users/users.ts

* Had previously inverted the naming structure of the serialization of List to help make an easier migration. Now that the bulk of the work of migrating to camelCase is complete we're making the swap to keep the naming in line with the rest of the types.
* DeseralizedList is becoming List and List is becoming ListResponse.
```
[ ] Yes
```

Rename DeserializedList to List

---

src/directory-sync/directory-sync.ts
src/directory-sync/interfaces/list-groups-options.interface.ts

* Part of an effort to move the naming of types from Group to the more specific DirectoryGroup.
```
[ ] Yes
```

Rename ListGroupsOptions to ListDirectoryGroupsOptions

---

src/common/serializers/event.serializer.ts
src/common/serializers/index.ts
src/directory-sync/directory-sync.spec.ts
src/directory-sync/interfaces/directory-user.interface.ts
src/directory-sync/serializers/directory-user.serializer.ts
src/directory-sync/utils/get-primary-email.spec.ts
src/webhooks/fixtures/webhook.json
src/webhooks/interfaces/index.ts
src/webhooks/interfaces/webhook-directory-group.interface.ts
src/webhooks/interfaces/webhook-directory-user.interface.ts
src/webhooks/interfaces/webhook-directory.interface.ts
src/webhooks/interfaces/webhook.interface.ts
src/webhooks/serializers/index.ts
src/webhooks/serializers/webhook-directory-group.serializer.ts
src/webhooks/serializers/webhook-directory-user.serializer.ts
src/webhooks/serializers/webhook-directory.serializer.ts
src/webhooks/webhooks.spec.ts
src/webhooks/webhooks.ts

* Part of a wider initiative to migrate our Node SDK to camel case for the 3.0.0 release.
* Migrates the Webhooks module to camel case.
```
[ ] Yes
```

Migrate Webhooks to camelCased

---

src/directory-sync/interfaces/directory.interface.ts

* Additionally adds some missing types to DirectoryType.
```
[ ] Yes
```

Switch Directory.type to DirectoryType instead of string

---

src/common/interfaces/at-least-one-property-of.interface.ts
src/common/interfaces/index.ts
src/users/interfaces/update-user-options.interface.ts
src/users/serializers/update-user-options.serializer.ts
src/users/users.spec.ts

`updateUser` options should require at least one property, not all properties to be passed. 
```
[ ] Yes
```

Fix `updateUser` options

---

src/directory-sync/directory-sync.spec.ts
src/directory-sync/interfaces/directory.interface.ts
src/directory-sync/serializers/directory.serializer.ts

* Now that we have a serialization layer in our Node SDK, we're able to start bypassing some of the legacy naming decisions that we've made. They key benefit here is that this will bring the API return types in line with our webhook return values.
* This is a breaking change our developers will need to handle when updating their SDKs.
```
[ ] Yes
```

Normalize DirectoryState to newer values

---

src/users/interfaces/create-user-options.interface.ts

Password is now optional when creating users in the API as of workos/workos#22384. This matches it.
```
[ ] Yes
```

Make password optional when creating users

---

src/common/interfaces/at-least-one-property-of.interface.ts
src/common/interfaces/index.ts
src/users/interfaces/update-user-options.interface.ts

This PR simplifies the `UpdateUserOptions` type.
The current type is too hard to type with non-static data, which severely limits its usability in real-world scenarios.
```
[ ] Yes
```

Simplify `UpdateUserOptions`

---

src/users/exceptions/index.ts
src/users/fixtures/list-users.json
src/users/fixtures/user.json
src/users/interfaces/user.interface.ts
src/users/serializers/user.serializer.ts
src/users/users.spec.ts

This PR removes the distinction between "Managed" and "Unmanaged" users from the SDK.
This concept is being removed from the API in the near future.
This is a breaking change to the User Management portion of the SDK.
Resolves USRLD-843.
```
[ ] Yes
```

Remove distinction between "Managed" and "Unmanaged" users

---

src/users/fixtures/user.json
src/users/interfaces/list-users-options.interface.ts
src/users/interfaces/user.interface.ts
src/users/serializers/user.serializer.ts
src/users/users.spec.ts

* The API has changed and we now send email_verified instead of email_verified_at in our User response. This is also now a boolean instead of a timestamp.
* The type was previously removed from Users and this change removes the now defunct type argument from listUsers.
* Fixes USRLD-900
```
[ ] Yes
```

Rename emailVerifiedAt to emailVerified and remove type arg from listUsers

---

src/users/interfaces/update-user-options.interface.ts
src/users/serializers/update-user-options.serializer.ts
src/users/users.spec.ts

Modify `updateUser` to use `email_verified` rather than `email_verified_at`

---

src/users/interfaces/index.ts
src/users/interfaces/verify-email-options.interface.ts
src/users/users.spec.ts
src/users/users.ts

* Changes the completeEmailVerification path and body to match the latest updates from the API. It now not only takes a token (now renamed to code) as an argument, but also requires the userId of the user.
* Fixes USRLD-849, USRLD-934
```
[ ] Yes
```

Migrate completeEmailVerification to verifyEmail

---

src/users/interfaces/index.ts
src/users/interfaces/magic-auth-challenge.interface.ts

* This interface is no longer used after all related endpoints were migrated to returning a User object instead.
```
[ ] Yes
```

Remove MagicAuthChallenge interface

---

src/users/interfaces/authenticate-user-with-magic-auth-options.interface.ts
src/users/serializers/authenticate-user-with-magic-auth-options.serializer.ts
src/users/users.spec.ts

* Updates to the latest state of the API.
```
[ ] Yes
```

Change magicAuthChallengedId to userId on authenticateUserWithMagicAuth

---

src/users/interfaces/send-magic-auth-code-options.interface.ts
src/users/serializers/send-magic-auth-code-options.serializer.ts
src/users/users.spec.ts

Update `sendMagicAuthCode` to take email rather than email_address

---

src/users/interfaces/authenticate-with-code-options.interface.ts
src/users/interfaces/authenticate-with-totp-options.interface.ts
src/users/serializers/authenticate-with-code-options.serializer.ts
src/users/serializers/authenticate-with-totp-options.serializer.ts

All authentication methods should pass `ipAddress` and `userAgent`

---

src/common/utils/pagination.ts

Our auto pagination doesn't currently respect a limit of 4 RPS (the limit on our `list_users` endpoint). This is a proposed fix, though it applies to all endpoints.
```
[ ] Yes
```

Add rate limiting to pagination

---

src/portal/interfaces/generate-portal-link-intent.interface.ts
src/portal/portal.spec.ts

Add domain verification intent enum and test
```
[ ] Yes
```

Add domain verification intent enum and test

---

src/user-management/interfaces/authenticate-with-magic-auth-options.interface.ts
src/user-management/serializers/authenticate-with-magic-auth-options.serializer.ts
src/user-management/user-management.spec.ts

```
[ ] Yes
```
* **PR #910** 👈

Add `link_authorization_code` parameter to `authenticateWithMagicAuth`

---

src/mfa/interfaces/challenge.interface.ts

```
[ ] Yes
```
* **PR #911** 👈

Fix `code` on `Challenge` which is incorrectly set as required

---

src/user-management/interfaces/authenticate-with-magic-auth-options.interface.ts
src/user-management/serializers/authenticate-with-magic-auth-options.serializer.ts
src/user-management/user-management.spec.ts

```
[ ] Yes
```
* **PR #915** 👈

Use `email` rather than `userId` on `authenticateWithMagicAuth` method

---

src/mfa/interfaces/factor.interface.ts
src/mfa/interfaces/totp.interface.ts
src/mfa/mfa.spec.ts
src/mfa/mfa.ts
src/mfa/serializers/factor.serializer.ts
src/mfa/serializers/totp.serializer.ts
src/user-management/fixtures/list-factors.json
src/user-management/interfaces/factor.interface.ts
src/user-management/serializers/factor.serializer.ts
src/user-management/serializers/index.ts
src/user-management/user-management.spec.ts
src/user-management/user-management.ts

Enrolling a TOTP auth factor always returns the `qrCode`, `secret`, and `uri` in the response, but retrieving and listing auth factors do not.
```
[ ] Yes
```
* **PR #929** 👈

Split out with and without secrets factors

---

src/directory-sync/interfaces/directory-user.interface.ts

"suspended" state is now deprecated and consolidated into the "inactive" state
```
[ ] Yes
```

Remove "suspended" state on Directory Sync user object

---

src/user-management/interfaces/authentication-response.interface.ts

There was a mismatch here where `organizationId` was marked as non-optional, when in it is actually an optional field in the response. [See related docs](https://workos.com/docs/reference/user-management/authentication/code).
```
[ ] Yes
```

`organizationId` should be optional in authentication responses

---

src/user-management/interfaces/update-user-options.interface.ts

Updates the `passwordHashType` parameter to `updateUser` to support the new `firebase-scrypt` type. More info can be found in the [migration guide](https://workos.com/docs/migrate/firebase/2-importing-users-into-workos/importing-passwords).
```
[ ] Yes
```

Add `firebase-scrypt` as valid `passwordHashType`

---

src/user-management/interfaces/authenticate-with-code-options.interface.ts
src/user-management/interfaces/authenticate-with-magic-auth-options.interface.ts
src/user-management/interfaces/authenticate-with-password-options.interface.ts
src/user-management/serializers/authenticate-with-code-options.serializer.ts
src/user-management/serializers/authenticate-with-magic-auth-options.serializer.ts
src/user-management/serializers/authenticate-with-password-options.serializer.ts

```
[x] Yes
```
I'll add the documentation for these params on the API and for the Node SDK all at once shortly.

Add `invitation_token` to authenticate endpoints

---

package.json

This PR updates the axios version to address a security update and changes the dependency constraint to allow for only patch updates to be installed
Resolves #936 
```
[ ] Yes
```

Update axios and change dependency constraint

---

src/common/utils/pagination.ts

This PR sets maximium limit of 100 records when auto paginating.
Right now, without the explicit limit being used in the auto pagination, we are paginating for every 10 records, making the pagination process too slow, discouraging our users to use this feature and implement their own instead. So we should use the maximum allowed and make this feature faster ourselves
```
[ ] Yes
```

Set maximium limit when auto paginating

---

src/directory-sync/directory-sync.ts

This PR fixes the return types for directory sync paginated methods that were using `List` to use `AutoPaginatable`
```
[ ] Yes
```

Fix return types for directory sync paginated methods

---

src/directory-sync/directory-sync.ts

Make sure that the options used when auto paginating use the correct options
```
[ ] Yes
```

Fix directory-sync options

---

src/webhooks/webhooks.ts

Fixes #964
There was a leftover usage of Node's `Buffer` API.
I have converted it to use the web platform's `TextEncoder` APIs instead.
I wonder if there's an ESLint plugin that could be used to lint for usages of APIs incompatible with cloudflare workers/edge runtime as it seems easy to let something through without thoroughly testing every single API call. A quick google search didn't bring much up so far.
```
[ ] Yes
```

Refactor Buffer usage

---

src/common/utils/fetch-client.ts
src/common/utils/test-utils.ts
src/workos.spec.ts

This is follow-up from the issue raised in #963 
```
[ ] Yes
```

Allow null body

---

src/common/interfaces/event.interface.ts
src/common/serializers/event.serializer.ts
src/user-management/fixtures/list-organization-memberships.json
src/user-management/fixtures/organization-membership.json
src/user-management/interfaces/organization-membership.interface.ts
src/user-management/serializers/organization-membership.serializer.ts
src/user-management/user-management.spec.ts

Adds new `status` attribute to the organization membership object, and adds the `organization_membership.updated` event.
```
[x] Yes
```
https://github.com/workos/workos/pull/25404

Add status to organization membership and updated event

---

.semaphore/semaphore.yml

Builds are now failing with a `ubuntu1804 is in brownout` error.
```
[ ] Yes
```

Upgrade semaphore image

---

src/user-management/interfaces/update-user-options.interface.ts

Updates the `passwordHashType` parameter to `updateUser` to support the new `ssha` type.
```
[ ] Yes
```

Add `ssha` as valid `passwordHashType`

---

src/common/interfaces/event.interface.ts
src/common/serializers/event.serializer.ts
src/common/utils/test-utils.ts
src/user-management/interfaces/authentication-response.interface.ts
src/user-management/interfaces/impersonator.interface.ts
src/user-management/interfaces/index.ts
src/user-management/interfaces/session.interface.ts
src/user-management/serializers/authentication-response.serializer.ts
src/user-management/serializers/session.serializer.ts
src/user-management/user-management.spec.ts

Adds support for the `impersonator` metadata in authentication responses, along with a new `user.impersonated` event.
```
[ ] Yes
```

Add impersonation fields and event

---

src/common/interfaces/event.interface.ts
src/common/serializers/event.serializer.ts

Adds session.created event.
Fixes https://linear.app/workos/issue/DAAP-424/add-sessioncreated-to-node
```
[ ] Yes
```

Add session.created event

---

setup-jest.ts

This PR resolves an issue where a TypeError occurs when trying to assign the 'crypto' property to the global object in a Jest test environment. The error occurred due to trying to get a read-only property from the global object.
The original error:
`TypeError: Cannot assign read-only property 'crypto' of object '[global object]'`
This was because the 'crypto' property already existed on the global object and was read-only.
To solve this problem I added an `if (!global.crypto)` check before assigning the 'crypto' property to the global object. This ensures that the 'crypto' property will only be set if it is not already set on the global object, thus avoiding the TypeError error.
Does this require changes to the WorkOS Docs? E.g. the [API Reference](https://workos.com/docs/reference) or …

Fix typeError on global.crypto assignment

---

.github/workflows/ci.yml

We are working on consolidating all CI to GitHub Actions.
```
[ ] Yes
```

Migrate repo to use GitHub Actions

---

.github/workflows/release.yml

This migrates the deploy step in Semaphore to also run in GitHub actions. This is set up to run automatically when we cut a new release (aka `git push --tags`) or you can manually trigger a release using the `Actions` tab.
This PR is set to only `--dry-run` the actual push because I can't actually test it until it's merged.
```
[ ] Yes
```

Deploy new versions to NPM when a new release is cut in GitHub

---

.github/workflows/fix-latest.yml

Users wanting to deploy a non-latest version will use this workflow to fix the @latest tag to the correct version once new release is published.
```
[ ] Yes
```

Provide a manual workflow for fixing the npm @latest tag

---

README.md

We are no longer relying on Semaphore for CI status, so need to update the badge.
```
[ ] Yes
```

Fix the README build status badge

---

src/events/events.spec.ts
src/events/interfaces/list-events-options.interface.ts

Make events array required for listEvents.
```
[x] Yes
```
https://github.com/workos/workos/pull/26139

Make events array required for listEvents

---

src/audit-logs/audit-logs.spec.ts

Builds have been failing due to [flakey tests](https://github.com/workos/workos-node/actions/runs/8618840279/job/23622148733). These are caused by calling `new Date()` sequentially which can sometimes result in a microsecond difference between results:
```
- Expected  - 1
+ Received  + 1
Object {
"createdAt": "2024-04-09T16:06:34.890Z",
"id": "audit_log_export_1234",
"object": "audit_log_export",
"state": "pending",
-   "updatedAt": "2024-04-09T16:06:34.890Z",
+   "updatedAt": "2024-04-09T16:06:34.891Z",
"url": undefined,
}
```
This fixes those tests by only grabbing a timestamp once.
```
[ ] Yes
```
If yes, link a related docs PR and add a docs …

Fix flakey audit_log tests

---

package.json

Our Volta version is quite a bit behind what we now specify is the minimum Node version in `engines`. This bumps the version in order to keep parity for development.
```
[ ] Yes
```

Bump volta node version to match `engines`

---

src/organizations/interfaces/create-organization-options.interface.ts
src/organizations/interfaces/domain-data.interface.ts
src/organizations/interfaces/index.ts
src/organizations/interfaces/update-organization-options.interface.ts
src/organizations/organizations.spec.ts
src/organizations/serializers/create-organization-options.serializer.ts
src/organizations/serializers/update-organization-options.serializer.ts

Add `domain_data` to Organization API and deprecate `domains`

---

src/events/events.spec.ts
src/events/interfaces/list-events-options.interface.ts
src/events/serializers/list-event-options.serializer.ts

Allow passing an `organizationId` into the options for the Events API 
```
[ ] Yes
```

Support `organizationId` as a valid parameter for `events`

---

src/common/interfaces/event.interface.ts
src/common/serializers/event.serializer.ts

Add om.created and om.deleted event types and mark om.added and om.removed as deprecated.
```
[ ] Yes
```

Add om.created and om.deleted event types

---

src/user-management/fixtures/invitation.json
src/user-management/fixtures/list-invitations.json
src/user-management/interfaces/invitation.interface.ts
src/user-management/serializers/invitation.serializer.ts

Exposes the `inviterUserId` field on the `invitation` object.
```
[ ] Yes
```

Add `inviterUserId` to `invitation`

---

src/user-management/fixtures/deactivate-organization-membership.json
src/user-management/interfaces/list-organization-memberships-options.interface.ts
src/user-management/interfaces/organization-membership.interface.ts
src/user-management/serializers/list-organization-memberships-options.serializer.ts
src/user-management/user-management.spec.ts
src/user-management/user-management.ts

Add organization membership deactivate and reactivate API methods.
```
[x] Yes (in progress)
```

Add organization membership deactivate and reactivate API methods

---

.github/workflows/release.yml

Pre-releases were grabbing their tags from `package.json`, when in a pre-release environment we want to use the tag itself.
```
[ ] Yes
```

Use name from release tag rather than package.json

---

.github/workflows/release.yml

npm doesn't let you publish multiple of the same version, but we also don't want to have to update package.json for every prerelease deploy we want to push. This change updates package.json to match the name of the tag triggering this beta deploy ensuring our versions are always unique.
I also reverted back to updating the `next` tag as that should always point to the latest pre-release build.
```
[ ] Yes
```

Pre-release deployments should use the version of the tag

---

src/user-management/__snapshots__/user-management.spec.ts.snap
src/user-management/interfaces/authenticate-with-code-options.interface.ts
src/user-management/interfaces/authorization-url-options.interface.ts
src/user-management/serializers/authenticate-with-code-options.serializer.ts
src/user-management/user-management.spec.ts
src/user-management/user-management.ts

Add PKCE parameters to User Management authentication methods in Node SDK
```
[X] Yes
```

Add PKCE parameters to User Management authentication methods in Node SDK

---

src/organizations/interfaces/create-organization-options.interface.ts
src/organizations/interfaces/update-organization-options.interface.ts

Marks `allow_profiles_outside_organization` as now being deprecated.
```
[ ] Yes
```

Mark `allow_profiles_outside_organization` as deprecated

---

package.json

It appears that the latest version of the `@workos-inc/node` package (7.11.2) has [introduced](https://github.com/workos/workos-node/pull/1062) some [changes](https://github.com/workos/workos-node/commit/e5292bff1380dc71b25e0a4ce585036737a5670b) that are causing the following error:
```
No "exports" main defined in /Users/user/Projects/app/node_modules/@workos-inc/node/package.json Error: No "exports" main defined in /Users/user/Projects/app/node_modules/@workos-inc/node/package.json
at exportsNotFound (node:internal/modules/esm/resolve:304:10)
at packageExportsResolve (node:internal/modules/esm/resolve:594:13)
at resolveExports (node:internal/modules/cjs/loader:592:36)
at Function.Module._findPath (node:internal/modules/cjs/loader:669:31)
at Function.Module._resolveFilename …
```

fix(package): add default exports for non-ESM projects

---

src/common/net/node-client.ts

Previously the client was passing the body directly down to the low level `write` and `byteLength` calls, which failed in cases where the body wasn't already serialized as a `string` or form of buffer.
This was not noticed on newer versions of Node since they include a global `fetch`, resulting in the SDK preferring the `FetchHttpClient`.
```
[ ] Yes
```

Fix `NodeHttpClient` handling of `URLSearchParam` request bodies 

---

src/user-management/interfaces/authentication-response.interface.ts
src/user-management/serializers/authentication-response.serializer.ts
src/user-management/user-management.spec.ts
src/user-management/user-management.ts

The refresh_token response used to be more limited, but that is no longer the case.
```
[ ] Yes
```

Update `grant_type=refresh_token` types

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/workos.ts

Releases a new `v7.17.0` version which includes:
- Add support for FGA endpoints https://github.com/workos/workos-node/pull/1077
```
[ ] Yes
```

Bump version to v7.17.0

---

src/user-management/interfaces/authenticate-with-refresh-token-options.interface.ts
src/user-management/serializers/authenticate-with-refresh-token.options.serializer.ts

Adds the new `organizationId` parameter to the `AuthenticateWithRefreshTokenOptions`.
```
[ ] Yes
```

Add `organizationId` parameter to `AuthenticateWithRefreshTokenOptions`

---

jest.config.js
package.json
src/worker.spec.ts
tsconfig.json

Adds a test in Miniflare, Cloudflare's dev environment for workers. Idea is that if the test runs and passes then the SDK should work in woeker environments.
```
[ ] Yes
```

Add test for worker environment

---

src/workos.ts

Use typeof to safely check Node process on workers.
```
[ ] Yes
```

Use typeof to safely check Node process on workers

---

src/user-management/user-management.spec.ts
src/user-management/user-management.ts

Add getLogoutUrlFromSessionCookie helper method.
```
[x] Yes
```

Add getLogoutUrlFromSessionCookie helper method

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/workos.ts

Bump to version 7.20.0.
Release contains:
* New `getLogoutUrlFromSessionCookie` helper method
* Fixes `process` ReferenceError on workers/edge 
```
[ ] Yes
```

Bump to version 7.20.0

---

src/user-management/interfaces/authenticate-with-session-cookie.interface.ts
src/user-management/interfaces/refresh-and-seal-session-data.interface.ts
src/user-management/interfaces/session-handler-options.interface.ts
src/user-management/user-management.ts

This matches the `authenticateWithRefreshToken` method which also accepts an `organizationId` to allow "switching".
```
[ ] Yes
```

Update `refreshAndSealSessionData` to accept `organizationId`

---

package.json

Fixes https://github.com/workos/workos-node/issues/1101
As per https://github.com/vercel/next.js/pull/66808, our imports weren't [correctly targeting](https://runtime-keys.proposal.wintercg.org/#workerd) Cloudflare Workers and Edge infrastructure. Now they are.
```
[ ] Yes
```

Add export types for CFW and Next.js 15

---

src/user-management/user-management.spec.ts
src/user-management/user-management.ts

They types were a slight lie, since you could have had a session with an org id in the access token the but the organization id in the sealed cookie data didn't include it. This required users to always decode the jwt even in cases where they were trying to abstract away using the new sealed session data. 
```
[ ] Yes
```

fix: Ensure organizationId is included in SessionCookieData during sealSessionDataFromAuthenticationResponse

---

src/portal/interfaces/generate-portal-link-intent.interface.ts
src/portal/portal.spec.ts

Adding the certificate renewal intent as an option for link generation
```
[ ] Yes
```

Add certificate renewal intent for Admin Portal intents

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/workos.ts

Releases a new version v7.23.0 which adds:
- https://github.com/workos/workos-node/pull/1104
```
[ ] Yes
```

Bump version to 7.23.0

---

src/common/interfaces/event.interface.ts
src/common/serializers/event.serializer.ts

Adds failed authentication events for SSO and OAuth
```
[ ] Yes
```

Add failed auth events for SSO and OAuth

---

src/user-management/interfaces/authenticate-with-session-cookie.interface.ts
src/user-management/interfaces/refresh-and-seal-session-data.interface.ts
src/user-management/session.spec.ts
src/user-management/session.ts
src/user-management/user-management.spec.ts
src/user-management/user-management.ts

Refactors the session helpers to add a new session class. The old helper methods will stay put, but we'll likely add a deprecation comment and remove them in a future major version.
See this [gist](https://gist.github.com/PaulAsjes/e1f80d5451f988db2acdf6ee894fcc46) as an example of how this would work in practise. 
```
[x] Yes
```

Rework session helpers

---

src/fga/fga.spec.ts
src/fga/fga.ts
src/fga/interfaces/check-op.enum.ts
src/fga/interfaces/check.interface.ts
src/fga/interfaces/index.ts
src/fga/interfaces/resource-op.enum.ts
src/fga/interfaces/resource.interface.ts
src/fga/serializers/check-options.serializer.ts
src/fga/serializers/resource.serializer.ts

- Add `batchWriteResources` method to FGA module
- Removes `Batch` from `CheckOp`
```
[x] Yes
```
https://github.com/workos/workos/pull/30160

Add batch write resources method

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/workos.ts

Releases a new version `v7.26.0` which includes:
- #1117 
```
[ ] Yes
```

Bump version to v7.26.0

---

src/fga/fga-live-test.spec.ts
src/fga/fga.ts
src/fga/interfaces/resource.interface.ts
src/fga/serializers/batch-write-resources-options.serializer.ts
src/fga/serializers/index.ts

- Adds a serializer for `BatchWriteResourcesOptions` to properly serialize options before making a request to `/fga/v1/resources/batch`
```
[ ] Yes
```

Serialize BatchWriteResourcesOptions before making request

---

src/common/interfaces/event.interface.ts
src/common/serializers/event.serializer.ts

Adds the `organization_domain.verified` and `organization_domain.verification_failed` events.
```
[ ] Yes
```

Add organization domain events

---

README.md

Updates the README to match the package import shown here https://workos.com/docs/reference/api-keys:
```
[ ] Yes
```

Update README.md import statement to match API reference

---

src/common/net/http-client.ts
src/index.worker.ts
src/workos.spec.ts
src/workos.ts

If you currently try to build a next project that uses workos-node you get the following error:
```
./node_modules/@workos-inc/node/lib/workos.js
A Node.js API is used (process.emitWarning at line: 178) which is not supported in the Edge Runtime.
```
This is because despite the fact that we have an if/else statement checking for whether `process` exists, the Next build step just sees a call to `process.emitWarning` and spits out that error. This moves the definition of `emitWarning` to the worker index.ts to prevent that error.
```
[ ] Yes
```

Make emitWarning safe for workers

---

src/index.ts
src/workos.ts

We previously made `emitWarning` a function which could be overridden to support JS runtimes that don't support `process.emitWarning`.  Unfortunately just having the method in the code (despite being overridden with a runtime safe alternative) isn't enough to prevent errors. This fixes that by switching to `console.warn` which should be supported everywhere.
Fixes https://github.com/workos/workos-node/issues/1138
```
[ ] Yes
```

Remove emitWarning entirely so Vercel deployments work

---

.gitignore
src/sso/__snapshots__/sso.spec.ts.snap
src/sso/interfaces/profile.interface.ts
src/sso/serializers/profile.serializer.ts
src/sso/sso.spec.ts

Adds `role` attribute to the profile object.
```
[X] Yes
```
[Docs PR](https://github.com/workos/workos/pull/31033)

Add `role` to profile

---

src/audit-logs/audit-logs.spec.ts
src/audit-logs/audit-logs.ts
src/audit-logs/interfaces/create-audit-log-schema-options.interface.ts
src/audit-logs/interfaces/index.ts
src/audit-logs/serializers/create-audit-log-schema-options.serializer.ts
src/audit-logs/serializers/create-audit-log-schema.serializer.ts
src/audit-logs/serializers/index.ts

Adds a `createSchema` method. Example use:
```ts
const schema = await workos.auditLogs.createSchema({
action: 'user.deleted',
actor: {
metadata: {
actor_id: 'string',
},
},
targets: [
{
type: 'user',
metadata: {
user_id: 'string',
},
},
],
metadata: {
foo: 'number',
baz: 'boolean',
},
});
console.log('schema created:', schema);
```
The above logs:
```ts
schema created: {
object: 'audit_log_schema',
version: 1,
targets: [ { type: 'user', metadata: [Object] } ],
actor: { metadata: { actor_id: 'string' } },
metadata: { baz: 'boolean', foo: 'number' },
createdAt: '2024-10-14T15:09:44.537Z'
}
```
```
[ ] Yes
```
If yes, link a related docs PR and add a docs …

Audit logs create schema

---

src/organization-domains/interfaces/organization-domain.interface.ts
src/organizations/fixtures/get-organization.json
src/organizations/interfaces/organization.interface.ts
src/organizations/organizations.spec.ts
src/organizations/serializers/organization.serializer.ts

* Makes `verificationToken` optional (it was always optional from the API's perspective)
* Correctly deserializes `verificationToken` and `verificationStrategy` when deserializing organizations
```
[ ] Yes
```

Fix organization domain interface

---

src/common/net/fetch-client.ts
src/common/net/http-client.ts
src/common/net/node-client.ts
src/fga/fga.spec.ts

- Adds network retries for FGA endpoints to `FetchHttpClient`
```
[ ] Yes
```

Add network retries for FGA endpoints 

---

src/workos.ts
tsconfig.json

Fixes https://github.com/workos/workos-node/issues/1149
Had to target a more recent version of ES to make TypeScript recognize the `options` argument of the [Error constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error).
```
[ ] Yes
```

Update TS target and provide better error messagins for http errors

---

src/common/net/node-client.ts

In the `NodeHttpClient`, `TypeError`s are considered retryable. However, if we get any other errors, we should reject with the given error.
```
[ ] Yes
```

Reject non-retryable error in node http client

---

package.json
src/common/net/fetch-client.spec.ts
src/common/net/node-client.spec.ts
src/fga/fga.spec.ts

- Adds tests for `NodeHttpClient` and `FetchHttpClient` to test network retries for the FGA module
- Removes retry test cases from FGA module unit tests
```
[ ] Yes
```

Add NodeHttpClient and FetchHttpClient tests for retry logic

---

src/actions/actions.spec.ts
src/actions/actions.ts
src/actions/fixtures/action-context.json
src/actions/interfaces/response-payload.ts
src/common/crypto/CryptoProvider.spec.ts
src/common/crypto/SignatureProvider.spec.ts
src/common/crypto/SignatureProvider.ts
src/common/crypto/index.ts
src/common/utils/unreachable.ts
src/index.ts
src/index.worker.ts
src/webhooks/webhooks.spec.ts
src/webhooks/webhooks.ts
src/workos.spec.ts
src/workos.ts

Introduce new methods for Actions:
- `signResponse`: Supports forming and signing actions responses from an actions endpoint
- `verifyHeader`: Supports incoming requests from WorkOS reaching actions endpoints  
Example usage:
```typescript
app.post("/registration-action", async (req, res) => {
const context = req.body;
// Verify incoming workos-signature 
try {
await workos.actions.verifyHeader({
payload: context,
sigHeader: req.headers["workos-signature"] as string,
secret: env.ACTIONS_SECRET,
});
} catch (err) {
return res.status(400).json({ error: "Invalid signature" });
}
let verdict: "allow" | "deny";
if (context.user_data.email.split("@")[1] === "gmail.com") {
verdict = "deny";
} else {
verdict = "allow";
}
// Sign the outgoing response using the actions secret 
const response = …
```

feat: Add actions support

---

src/user-management/interfaces/authentication-response.interface.ts

Adds `'Passkey'` as a possible value of `AuthenticationMethod`.
```
[ ] Yes
```

Add `Passkey` to `AuthenticationMethod` union

---

src/audit-logs/audit-logs.spec.ts
src/audit-logs/interfaces/create-audit-log-schema-options.interface.ts
src/audit-logs/serializers/create-audit-log-schema-options.serializer.ts
src/audit-logs/serializers/create-audit-log-schema.serializer.ts

Make metadata optional when creating audit log schema.
```
[ ] Yes
```

Make metadata optional when creating audit log schema

---

src/user-management/session.ts

Fixes issue where:
- If you create a new session without an org
- Then refresh with an orgId 
- Then on the next refresh it no longer maintains the orgId
This was an issue in the old refreshAndSealSessionData and was fixed https://github.com/workos/workos-node/blob/08ab75f210b11371fa4de78eb97f35d2deb90a5c/src/user-management/user-management.ts#L504
Note: Having a deeper think about this, its weird that this is not required when a session is initiated with an orgId from the start which makes me think potentially there is an issue that when an refresh with orgId is sent to the workOs backend the orgId isn't actually persisted which breaks the normal refresh flow. This theory potentially also explains why in the scenario above after the switch org happens the workos portal still doesn't show …

fix: Update session.refresh to correctly maintain previous orgId

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/workos.ts

Bump version for new Action deserializing function
```
[ ] Yes
```

Bump to v7.35.0

---

src/common/iron-session/edge-iron-session-provider.ts
src/common/iron-session/web-iron-session-provider.ts

iron-session has a default ttl of 14 days, which is problematic in the edge case where a user has set their WorkOS sessions to expire > 14 days. In that scenario, iron-session will expire first, making unsealing impossible which means you can't refresh the session.
This fix changes the default ttl to 0, which sets it to the max of ~10 years.
```
[ ] Yes
```

Use a non-default ttl with iron-session

---

src/common/serializers/event.serializer.ts
src/organizations/fixtures/list-organization-roles.json
src/organizations/interfaces/list-organization-roles-options.interface.ts
src/organizations/organizations.spec.ts
src/organizations/organizations.ts
src/roles/interfaces/role.interface.ts
src/roles/serializers/role.serializer.ts
src/user-management/serializers/role.serializer.ts

Add GET /organization/:orgId/roles support.
```
[ ] Yes
```

Add GET /organization/:orgId/roles support

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/user-management/user-management.ts
src/workos.ts

By default, jose sets a `cooldownDuration` to 30 seconds for JWKS cache. This PR changes it to 5 minutes.
```
[ ] Yes
```

set JWKS cache duration to 5 minutes

---

src/actions/actions.spec.ts
src/actions/fixtures/authentication-action-context.json
src/actions/fixtures/user-registration-action-context.json
src/actions/interfaces/action.interface.ts
src/actions/serializers/action.serializer.ts

When Radar is enabled, the device fingerprint captured by Radar is forwarded in action request payloads. This PR adds the attribute to action interfaces.
```
[ ] Yes
```

Add device fingerprint to action context payloads

---

src/user-management/session.spec.ts
src/user-management/session.ts
src/user-management/user-management.spec.ts
src/user-management/user-management.ts

Adds a new optional `returnTo` option to `userManagement.getLogoutUrl` to support the upcoming Logout URIs feature.
```
[ ] Yes
```

Add `returnTo` option to `userManagement.getLogoutUrl`

---

src/actions/actions.spec.ts
src/actions/actions.ts
src/common/crypto/index.ts

Remove a barrel file that was importing Node-specific libraries, unnecessarily causing compatibility issues with this library when running from Cloudflare workers.
This issue first appeared in workos/authkit-nextjs#187.
```
[ ] Yes
```
This wasn't caught by the `npm run test:worker` test. Manually testing with wrangler, I can see that the code fails when the `NodeCryptoProvider` is imported (via the barrel file):
With this change, there are no errors when running `wrangler dev`.

Fix library compatibility with workers environment

---

.github/workflows/coana-guardrail.yml

Update the Coana Guardrail to no longer require an API key to run. This allows for forks of public repos such as this one to run successfully.
```
[ ] Yes
```

Update Coana Guardrail to not require API key for run

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/workos.ts

Bump to version 7.37.2 to add missing type re-exports.
```
[ ] Yes
```

Bump to version 7.37.2

---

src/organizations/fixtures/list-organization-roles.json
src/organizations/organizations.spec.ts
src/roles/interfaces/role.interface.ts
src/roles/serializers/role.serializer.ts
src/user-management/serializers/role.serializer.ts

Deserialize missing permissions, created at, and updated at fields on role events and add permissions to org. roles API response.
```
[x] Yes (API reference)
```

Add permissions to roles events and API

---

src/user-management/interfaces/refresh-and-seal-session-data.interface.ts
src/user-management/session.spec.ts
src/user-management/session.ts

Update Session#refresh() to return all JWT claims.
```
[x] Yes (API reference)
```

Update Session#refresh() to return all JWT claims

---

src/fga/fga.spec.ts
src/fga/interfaces/check.interface.ts

Now that the [FGA Check endpoint](https://workos.com/docs/reference/fga/check) returns the [Warrant Token](https://workos.com/docs/fga/warrant-tokens) that was used during evaluation of the check, this PR updates the Node SDK to expose the newly returned value to the caller.
```
[X] Yes
```
https://github.com/workos/workos/pull/34558

Expose the `warrant_token` attribute returned by the FGA check endpoint to the caller

---

src/user-management/fixtures/list-users.json
src/user-management/fixtures/user.json
src/user-management/interfaces/user.interface.ts
src/user-management/serializers/user.serializer.ts
src/user-management/user-management.spec.ts

https://linear.app/workos/issue/AUTH-4131/update-workos-node-sdk-for-last-sign-in-at
adds `lastSignInAt` to user
```
[X] Yes
```
docs PR: https://github.com/workos/workos/pull/35170

add lastSignInAt to user

---

src/common/interfaces/event.interface.ts
src/common/serializers/event.serializer.ts

This event is [never emitted](https://work-os.slack.com/archives/C07CZA4UJ81/p1721849550636049) so we are officially deprecating. 
Does this require changes to the WorkOS Docs? E.g. the [API Reference](https://workos.com/docs/reference) or code snippets need updates. 
```
[ ] Yes
```
No this was removed from the docs [in this PR](https://github.com/workos/workos/pull/18924) and removed from the dashboard [in this PR](https://github.com/workos/workos/pull/29101).

Remove `dsync.deactivated` event

---

src/actions/actions.spec.ts
src/user-management/interfaces/create-user-options.interface.ts
src/user-management/interfaces/update-user-options.interface.ts
src/user-management/interfaces/user.interface.ts
src/user-management/serializers/create-user-options.serializer.ts
src/user-management/serializers/update-user-options.serializer.ts
src/user-management/serializers/user.serializer.ts

Allows adding one during create and update and includes the externalId in the user object.
```
[x] Yes
```
^ docs are coming but looking to get this out in a preview release ahead of time.

Add externalId support to user

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/workos.ts

Includes #1228 and #1229 to support using externalId on users.
```
[ ] Yes
```

Bump version to 7.40.0

---

src/actions/actions.spec.ts
src/organizations/interfaces/create-organization-options.interface.ts
src/organizations/interfaces/organization.interface.ts
src/organizations/interfaces/update-organization-options.interface.ts
src/organizations/organizations.spec.ts
src/organizations/organizations.ts
src/organizations/serializers/create-organization-options.serializer.ts
src/organizations/serializers/organization.serializer.ts
src/organizations/serializers/update-organization-options.serializer.ts

Deserializes it from the api response, allows creating and updating organizations with an external id, and provides a
getOrganizationByExternalId function.
```
[x] Yes
```
Documentation coming soon

Add external id support for organizations

---

package.json
src/sso/__snapshots__/sso.spec.ts.snap
src/workos.ts

Adds support for external id on organizations from #1232 
```
[ ] Yes
```

Bump version to 7.41.0

---

src/actions/actions.spec.ts
src/organizations/fixtures/get-organization.json
src/organizations/interfaces/create-organization-options.interface.ts
src/organizations/interfaces/organization.interface.ts
src/organizations/interfaces/update-organization-options.interface.ts
src/organizations/organizations.spec.ts
src/organizations/serializers/create-organization-options.serializer.ts
src/organizations/serializers/organization.serializer.spec.ts
src/organizations/serializers/organization.serializer.ts
src/organizations/serializers/update-organization-options.serializer.ts
src/user-management/fixtures/user.json
src/user-management/interfaces/create-user-options.interface.ts
src/user-management/interfaces/update-user-options.interface.ts
src/user-management/interfaces/user.interface.ts
src/user-management/serializers/create-user-options.serializer.ts
src/user-management/serializers/update-user-options.serializer.ts
src/user-management/serializers/user.serializer.spec.ts
src/user-management/serializers/user.serializer.ts
src/user-management/user-management.spec.ts

Supports passing metadata on updating and creation of both as well.
Right now the API doesn't always return metadata, but it will eventually always return empty object if there is none, and so I've made it so that users and organizations will always have a metadata object after deserialization.
```
[ ] Yes
```

Add metadata to organizations and users

---

src/common/utils/pagination.spec.ts
src/common/utils/pagination.ts
src/directory-sync/directory-sync.ts
src/fga/fga.ts
src/organizations/organizations.ts
src/sso/sso.ts
src/user-management/user-management.ts

Adds tests and updates typing for pagination utils.
```
[ ] Yes
```

Add tests and typing updates for pagination utils

---

src/user-management/interfaces/list-organization-memberships-options.interface.ts

Make `userId` or `organizationId` required when calling list org. memberships, which is how the API is designed. This came up recently in a triage thread, but is a semi-breaking change, so adding to v8 branch.
```
[ ] Yes
```

Make userId or organizationId required when calling listOrganizationMemberships

---

.github/workflows/coana-analysis.yml

In light of the [recent compromise of the tj-actions/changed-files action](https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised), we’re trying to reduce the risk incurred from our use of third-party actions. 
[GitHub documentation](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) recommends pinning third-party actions to a full length commit SHA as a good security practice, and as the only way to use an action as an immutable release.
This PR pins this repository’s third-party actions to their currently used version’s commit SHA, as indicated in the logs for the most recent workflow runs, or from the most recent matching release if logs are not …

Pin third-party actions to currently used SHA

---

src/organization-domains/fixtures/get-organization-domain-pending.json
src/organization-domains/fixtures/get-organization-domain-verified.json
src/organization-domains/interfaces/organization-domain.interface.ts
src/organization-domains/organization-domains.spec.ts
src/organization-domains/serializers/organization-domain.serializer.ts

Add `organizationId` to the response as indicated in work-os-playground-domain-verification-v4hbbh
```
[ ] Yes
```

Add organizationId to organization domain

---

src/user-management/interfaces/authorization-url-options.interface.ts
src/user-management/user-management.ts

We no longer need applications' initiate login endpoints to return the `context` query parameter when getting the authorization URL. This PR deprecates that option from the `getAuthorizationUrl` and `signIn` functions and prints a message to the console when it's used. In a future release, we can remove this option entirely.

Deprecate `context` option on `getAuthorizationUrl`

---

src/vault/cryptography/decrypt.ts
src/vault/cryptography/encrypt.ts
src/vault/vault-live-test.spec.ts
src/vault/vault.ts

Add an optional parameter to the Vault local encrypt/decrypt functions for additionally authenticated data.
```
[x] Yes
```
https://github.com/workos/workos/pull/38690

Support optional authenticated data in local encrypt/decrypt

---

src/user-management/interfaces/update-user-options.interface.ts
src/user-management/user-management.spec.ts

We say in our [docs](https://workos.com/docs/user-management/metadata/add-and-update-metadata) that to remove a metadata field, you should set the value to null:
> To delete a metadata attribute, set the key to null in the metadata object of the request body.
This works via Postman. However, in our workos-node SDK, we have the TS interface set to only accept string values for the metadata object ([here](https://github.com/workos/workos-node/blob/16a31c8605bc91c66616e7e54dd15c0ec2b7da66/src/user-management/interfaces/update-user-options.interface.ts#L12)).
This PR adds `null` to the`UpdateUserOptions` and `SerializedUpdateUserOptions` interfaces and adds one test. 
No docs changes needed
I would love eyes on my test - I am pretty sure it is correctly testing that the key is removed from …

Allow null value metadata

---

src/common/utils/env.ts
src/user-management/user-management.ts

This pull request introduces a cross-runtime utility for accessing environment variables and updates the `UserManagement` class to use this utility for improved runtime compatibility and code consistency.
* Added a new helper function, `getEnv`, in `src/common/utils/env.ts`. This function retrieves environment variables across different runtimes, including Node.js, Deno, and Cloudflare Workers, with support for a default value.
* Replaced direct usage of `process.env` with the new `getEnv` utility for the `cookiePassword` parameter in the `authenticateWithSessionCookie` and `getSessionFromCookie` methods. This ensures compatibility with multiple runtimes. [[1]](diffhunk://#diff-5df813524b03843b7a76359f2c080a36e82f2c065c578794071eb6ffcc0efa7cL394-R395) …

[v8] Add other runtime checks for environment variables

---

src/common/interfaces/event.interface.ts
src/common/serializers/event.serializer.ts

Add the session.revoked event
```
[ ] Yes
```

Add session revoked event

---

src/common/interfaces/event.interface.ts
src/common/serializers/event.serializer.ts
src/organization-domains/interfaces/organization-domain.interface.ts
src/organization-domains/serializers/organization-domain.serializer.ts

Independent organization_domain events for created, updated, and deleted are available in the dashboard. 
This PR updates the node sdk to support those events
```
[x] Yes
```
Docs PR: 
https://github.com/workos/workos/pull/39990

add organization_domain created/updated/deleted events

---

src/common/exceptions/parse-error.ts
src/workos.spec.ts
src/workos.ts

Some customers have reported receiving non-json responses from the workos API. These raise a syntax error when the Node.js ADK attempts to parse the json. This PR adds rawBody and requestID to a new ParseError exception for debugging purposes.

Add ParseError to include rawBody and requestID for debugging purposes

---

src/common/exceptions/parse-error.ts
src/common/net/fetch-client.spec.ts
src/common/net/fetch-client.ts
src/workos.ts

Missed a codepath in #1313 where non-200 responses would attempt to parse the body

Raise ParseError if non-200 response returns invalid JSON

---

src/organizations/fixtures/list-organization-feature-flags.json
src/organizations/interfaces/feature-flag.interface.ts
src/organizations/interfaces/index.ts
src/organizations/interfaces/list-organization-feature-flags-options.interface.ts
src/organizations/organizations.spec.ts
src/organizations/organizations.ts
src/organizations/serializers/feature-flag.serializer.ts

Add GET /organizations/:orgId/feature-flags support
```
[x] Yes
```

Add GET /organizations/:orgId/feature-flags support

---

src/organizations/organizations.spec.ts
src/organizations/organizations.ts

- Fixed incorrect URL path for organization feature flags endpoint (changed `feature_flags` to `feature-flags`)
- Updated corresponding tests to match the correct endpoint format
Closes #1334

Fix feature flags endpoint URL

---

.gitignore
README.md
bin/restore-or-install
package-lock.json
package.json

We should be checking in the lockfile to ensure dependencies are consistent across environments. Since we use npm in CI it seems to make sense that we use it on the development side as well.
```
[ ] Yes
```

Check in lockfile and use npm consistently

---

src/sso/__snapshots__/sso.spec.ts.snap
src/sso/interfaces/authorization-url-options.interface.ts
src/sso/sso.spec.ts
src/sso/sso.ts

- Add `provider_query_params` parameter to SSO `getAuthorizationUrl` method
- Implement consistent query string serialization with UserManagement module
- Add comprehensive tests for the new functionality
- **Interface**: Added `providerQueryParams` to `SSOAuthorizationURLOptions`
- **Implementation**: Updated SSO class to handle provider query params using `qs.stringify`
- **Tests**: Added test coverage for both populated and empty provider query params
- **Compatibility**: Fixed empty `providerScopes` array handling to maintain backward compatibility
Resolves ENT-3776

Add `provider_query_params` to `getAuthorizationUrl` method

---

src/widgets/interfaces/get-token.ts

This was accidentally typed as a single-item tuple, so passing multiple scopes currently results in a type error.
```
[ ] Yes
```

Fix `GetTokenOptions[scopes]` type

---

src/common/interfaces/workos-options.interface.ts
src/common/net/fetch-client.spec.ts
src/common/net/fetch-client.ts
src/index.ts
src/workos.ts

`fetch` does not have a default timeout, so there is a non-zero chance of our HTTP requests to WorkOS servers hanging indefinitely. This PR introduces `timeout` as an optional parameter while initializing WorkOS client to terminate the request if its taking longer than `timeout` milliseconds. 
```
[ ] Yes
```

Add timeout to http client requests

---

.github/workflows/ci.yml
.github/workflows/fix-latest.yml
.github/workflows/release.yml
.github/workflows/runtime-tests.yml
README.md
package-lock.json
package.json

This pull request updates the project's Node.js version requirements and related configuration files to use Node.js 20 or newer, and removes support for Node.js 18. These changes help ensure compatibility with the latest Node.js features and security updates.
**Node.js version updates:**
* Updated the required Node.js engine in `package.json` from `>=18` to `>=20`.
* Changed the `@types/node` development dependency in `package.json` from version `~18` to `~20`.
**CI/CD workflow updates:**
* Modified the matrix in `.github/workflows/ci.yml` to run tests only on Node.js versions 20, 22, and 24, removing Node.js 18.
* Updated the Node.js version used in `.github/workflows/fix-latest.yml`, `.github/workflows/release.yml`, and `.github/workflows/runtime-tests.yml` from 18 to 22. …

[v8] drop node 18
